// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Thu Aug 17 14:20:21 2017

VGA_Submarino VGA_Submarino_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.areaAtiva(areaAtiva_sig) ,	// input  areaAtiva_sig
	.linha(linha_sig) ,	// input [9:0] linha_sig
	.coluna(coluna_sig) ,	// input [9:0] coluna_sig
	.posicoesEmbarcacao(posicoesEmbarcacao_sig) ,	// input [63:0] posicoesEmbarcacao_sig
	.rgb_r(rgb_r_sig) ,	// output  rgb_r_sig
	.rgb_g(rgb_g_sig) ,	// output  rgb_g_sig
	.rgb_b(rgb_b_sig) 	// output  rgb_b_sig
);

defparam VGA_Submarino_inst.X1 = 'b0000000001;
defparam VGA_Submarino_inst.X2 = 'b0000000010;
defparam VGA_Submarino_inst.X3 = 'b0000000011;
defparam VGA_Submarino_inst.X4 = 'b0000000100;
defparam VGA_Submarino_inst.X5 = 'b0000000101;
defparam VGA_Submarino_inst.X6 = 'b0000000110;
defparam VGA_Submarino_inst.X7 = 'b0000000111;
defparam VGA_Submarino_inst.X8 = 'b0000001000;
defparam VGA_Submarino_inst.Y1 = 'b0000000001;
defparam VGA_Submarino_inst.Y2 = 'b0000000010;
defparam VGA_Submarino_inst.Y3 = 'b0000000011;
defparam VGA_Submarino_inst.Y4 = 'b0000000100;
defparam VGA_Submarino_inst.Y5 = 'b0000000101;
defparam VGA_Submarino_inst.Y6 = 'b0000000110;
defparam VGA_Submarino_inst.Y7 = 'b0000000111;
defparam VGA_Submarino_inst.Y8 = 'b0000001000;
